### PR TITLE
Prelude updates

### PR DESCRIPTION
**Pull request by bebaps**
- reformatted the file structure to match what myself and Matt discussed
- normalized the formatting across files
- simplified some of the theme files where applicable
- updated the gulpfile to add a local server via browsersync & sourcemaps
- other small tweaks

### CODE REVIEW

**Comment by buschschwick** [comment]
I'm not sure how I feel about including `hero.php` by default. It seems to lean a little too close to a style decision and not so much a code foundation. Just because a post or a page has a featured image doesn't mean a developer/designer will want that as a banner image in it's own section. (case in point: Techpinions: https://techpinions.com/unpacked-global-ad-blocker-usage-on-smartphones/43214 - uses featured image for grid view but single shows none)  Thoughts @mattada / @bebaps

**Comment by bebaps** [comment]
@buschschwick I don't see it that way. If we can take `hero.php` out, then on the same judgement we can also take out any other file that already has code in it - should we then take out `archive.php` because the developer/designer might not want to display their archive in the same manner that we do?

The hero is included because a large majority of projects that we design have some sort of hero in them. My approach to our starter theme is just that, it is our starter theme, our own go to setup. If there are common features of the projects we regularly make, why take those out?

As we are choosing to share it, it is expected that if anyone else wants to use it, they will download/fork it and make changes as needed to fit their situation. If someone doesn't want to use the hero on a particular template file, it is only one line of code they need to remove.

**Comment by buschschwick** [comment]
I don't really think that's the same argument. Archive.php is a general Wordpress function/expected file where as a page hero is not. I feel the approach should be add things if you need them, not take them out if you don't. The reason we used ours/this framework in the first place is to stay away from bloat and unwanted features. 

While I understand that a lot of our sites have a hero option, I just don't feel it fits in what our framework is trying to accomplish which is a simple, lightweight, frame work to start from.

**Comment by mattada** [comment]
I am with Eric on this. Hero is a design function where archive is a core feature. 


#Sentfrommyiphone
Matt Adams
6025097553

Creative Director
factor1studios.com

**Pull request closed without merging**
